# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ubuntu:16.04
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      ZK_BUILD_NUMBER: 3.5.5-badh1
    
    steps:
      - run: apt-get update && apt-get upgrade -y && apt-get install -y git curl

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.xml" }}
          - v1-dependencies-

      - run: apt-get install -y maven openjdk-8-jdk ant automake build-essential libcppunit-dev libtool
      - run: ant tar
      - run: mvn install:install-file -Dfile=/root/repo/build/zookeeper-$ZK_BUILD_NUMBER.jar -DgroupId=org.apache.zookeeper -DartifactId=zookeeper -Dversion=$ZK_BUILD_NUMBER -Dpackaging=jar

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.xml" }}

      # run tests!
      # - run: mvn integration-test

      - store_artifacts:
          path: /root/repo/build
          destination: badh-zookeeper-bin
